### PR TITLE
Use jsDelivr instead

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## Type
What type of Pull request is this?

- [ ] **New Icons**  
  Types: `_____` 
- [ ] **Updating existing icons**  
  Icon: `_____` 
- [x] **Small corrections**  
  Correcting typos, wrong licenses, file names, etc.

## Description

I prefer [jsDelivr](https://www.jsdelivr.com/) instead of raw.githubusercontent.com

Features:
- four CDN & two DNS providers
- Version Aliasing (Instead of using a unique URL for each version to load a project with jsDelivr you can use aliasing.)
- Load multiple files with a single HTTP request (`https://cdn.jsdelivr.net/combine/gh/jquery/jquery@3.2/dist/jquery.min.js,gh/twbs/bootstrap@3.3/dist/js/bootstrap.min.js`)
- Auto-Updates (jsDelivr libgrabber is a utility that is going to run on our servers and can auto-update all hosted projects if configured.)

For more info see [jsDelivr offical website](https://www.jsdelivr.com/features) and [article on "jsDelivr – The advanced open source public CDN"](https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/)
```
serving ~ 3450 TiB / month
```

Closes #

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
@abhijoshi2k I also want your opinion.

**Comment by abhijoshi2k** [comment]
I think both are fine. I really doubt if people are going to load multiple images with 1 CDN. Most probably they're gonna use separate ones only. Also, these icons aren't that heavy to load.

**Comment by PuneetGopinath** [comment]
> I think both are fine. I really doubt if people are going to load multiple images with 1 CDN. Most probably they're gonna use separate ones only. Also, these icons aren't that heavy to load.

I simply mentioned the features, if you load two icons it will not work, it is for js and css files. jsDelivr has a short url (not very short), very fast, these features are useful for us

**Comment by abhijoshi2k** [comment]
I never said features aren't useful. I just felt that we don't really need them in this case. Let's see what @Andre601 has to say. If he agrees, then we'll have a majority I guess. Then we'll merge.

**Comment by Andre601** [comment]
Did you try if it works as expected?
Also, are there any kind of limits on requests?

**Comment by PuneetGopinath** [comment]
> Did you try if it works as expected?
> Also, are there any kind of limits on requests?

No limits, It's live on my profile readme!!

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Plz review

**Pull request merged**
