### PR TITLE
Add wave gif

### PR DESCRIPTION
**Pull request by PuneetGopinath**

### CODE REVIEW

**Comment by Andre601** [comment]
Won't merge for some reasons:

1. The info should be in the main README, so that people have an easy way to find and use it.
2. The gif is way too large. Size should conform to the Contributing Guidelines which is 16x16 pixels at most.

**Comment by PuneetGopinath** [comment]
Ok, anyway the info is main readme only

**Comment by PuneetGopinath** [comment]
@Andre601 Check out the update I made!!

**Review by Andre601 — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
Hey @Andre601 you did some commits on branch main why didn't you say me to pull branch main

**Comment by PuneetGopinath** [comment]
List of those commits:
- https://github.com/Readme-Workflows/Readme-Icons/commit/5b5952e866fe239607f24a1543e7b3903ff270d7
- https://github.com/Readme-Workflows/Readme-Icons/commit/e3b057351a6f906ac08fa7abe1f4db83f647c511
- https://github.com/Readme-Workflows/Readme-Icons/commit/2db215356ca4155826b7314deacef8aa42fffe39
- https://github.com/Readme-Workflows/Readme-Icons/commit/e798cc31d3cd9bb8dcb9caa8b85d314e3a4b76bc

**Comment by PuneetGopinath** [comment]
Did you do some magic, you didn't rebase or pull branch main but the commits on branch main still exist?

**Pull request merged**
